/**
 * BlockNote editor — client-only (ProseMirror needs a real DOM; the route
 * mounts this behind ClientOnly + lazy so it never renders during SSR and
 * never ships in the worker's server bundle).
 *
 * UI package: @blocknote/shadcn (v0.52 targets Tailwind v4 natively; its
 * utility classes are generated by our build via @source in styles.css and
 * resolve against the shadcn theme variables already defined there).
 * Persistence: publishing exports blocks → markdown (lossy) → record
 * textContent; drafts store the block JSON itself (lossless) and load it
 * back via `initialBlocks`.
 */
import "@blocknote/shadcn/style.css";

import type { BlockNoteEditor, PartialBlock } from "@blocknote/core";
import { useCreateBlockNote } from "@blocknote/react";
import { BlockNoteView } from "@blocknote/shadcn";
import { useEffect, useRef, useState } from "react";

export type { BlockNoteEditor };

export default function Editor({
  initialMarkdown,
  initialBlocks,
  onChange,
  onReady,
}: {
  /** Markdown to load into the editor (edit flow); parsed via BlockNote's built-in parser. */
  initialMarkdown?: string;
  /** Draft blocks to load (resume flow); wins over initialMarkdown. */
  initialBlocks?: unknown[];
  /** Fires on every document change (user edits AND programmatic loads). */
  onChange?: () => void;
  onReady: (editor: BlockNoteEditor) => void;
}) {
  const editor = useCreateBlockNote();
  // Initial content is applied exactly once per editor instance — a re-run
  // of the effect (e.g. a parent re-render changing a callback identity)
  // must never clobber what the writer has typed since.
  const appliedRef = useRef(false);

  useEffect(() => {
    if (!appliedRef.current) {
      appliedRef.current = true;
      if (initialBlocks && initialBlocks.length > 0) {
        // Draft rows are written by our own editor, but guard the cast: a
        // malformed row falls back to an empty editor instead of a crash.
        try {
          editor.replaceBlocks(
            editor.document,
            initialBlocks as PartialBlock[],
          );
        } catch {
          // start empty
        }
      } else if (initialMarkdown) {
        const blocks = editor.tryParseMarkdownToBlocks(initialMarkdown);
        if (blocks.length > 0) editor.replaceBlocks(editor.document, blocks);
      }
    }
    onReady(editor);
  }, [editor, initialMarkdown, initialBlocks, onReady]);

  // BlockNote paints its own surface and needs to be told which edition it is
  // in. This was pinned to "light", which is why the editor stayed a white box
  // on a dark page no matter how many tokens were overridden around it — the
  // component was never reading them.
  return (
    <BlockNoteView editor={editor} onChange={onChange} theme={useEdition()} />
  );
}

/**
 * The edition currently in force, mirroring the pre-paint bootstrap in
 * `__root`. Subscribes to the attribute so a writer switching Appearance in
 * another tab — or the system flipping at dusk while on "System" — repaints the
 * editor rather than stranding it in the wrong one.
 */
function useEdition(): "light" | "dark" {
  const [edition, setEdition] = useState<"light" | "dark">(() =>
    typeof document === "undefined"
      ? "light"
      : document.documentElement.dataset.theme === "dark"
        ? "dark"
        : "light",
  );
  useEffect(() => {
    const read = () =>
      setEdition(
        document.documentElement.dataset.theme === "dark" ? "dark" : "light",
      );
    read();
    const observer = new MutationObserver(read);
    observer.observe(document.documentElement, {
      attributeFilter: ["data-theme"],
    });
    return () => observer.disconnect();
  }, []);
  return edition;
}
