/**
 * BlockNote editor — client-only (ProseMirror needs a real DOM; the route
 * mounts this behind ClientOnly + lazy so it never renders during SSR and
 * never ships in the worker's server bundle).
 *
 * UI package: @blocknote/shadcn (v0.52 targets Tailwind v4 natively; its
 * utility classes are generated by our build via @source in styles.css and
 * resolve against the shadcn theme variables already defined there).
 * Persistence: blocks → markdown (lossy export) → record textContent.
 */
import "@blocknote/shadcn/style.css";

import type { BlockNoteEditor } from "@blocknote/core";
import { useCreateBlockNote } from "@blocknote/react";
import { BlockNoteView } from "@blocknote/shadcn";
import { useEffect } from "react";

export type { BlockNoteEditor };

export default function Editor({
  initialMarkdown,
  onReady,
}: {
  /** Markdown to load into the editor (edit flow); parsed via BlockNote's built-in parser. */
  initialMarkdown?: string;
  onReady: (editor: BlockNoteEditor) => void;
}) {
  const editor = useCreateBlockNote();

  useEffect(() => {
    if (initialMarkdown) {
      const blocks = editor.tryParseMarkdownToBlocks(initialMarkdown);
      if (blocks.length > 0) editor.replaceBlocks(editor.document, blocks);
    }
    onReady(editor);
    // Re-init only when a different editor instance is created.
  }, [editor, initialMarkdown, onReady]);

  return <BlockNoteView editor={editor} theme="light" />;
}
