/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LeavingSubstackRouteImport } from './routes/leaving-substack'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as OpenRouteImport } from './routes/open'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WriteRouteImport } from './routes/write'
import { Route as AtChar123handleChar125IndexRouteImport } from './routes/@{$handle}.index'
import { Route as AtChar123handleChar125RkeyRouteImport } from './routes/@{$handle}.$rkey'
import { Route as AtChar123handleChar125RssDotxmlRouteImport } from './routes/@{$handle}.rss[.]xml'
import { Route as ApiDraftsRouteImport } from './routes/api.drafts'
import { Route as ApiImportRouteImport } from './routes/api.import'
import { Route as ApiPublishRouteImport } from './routes/api.publish'
import { Route as ApiReportRouteImport } from './routes/api.report'
import { Route as ApiStatsRouteImport } from './routes/api.stats'
import { Route as ApiSubscriptionRouteImport } from './routes/api.subscription'
import { Route as ApiWaitlistRouteImport } from './routes/api.waitlist'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as OauthClientMetadataDotjsonRouteImport } from './routes/oauth.client-metadata[.]json'
import { Route as OauthJwksDotjsonRouteImport } from './routes/oauth.jwks[.]json'
import { Route as ApiAccountDeleteRouteImport } from './routes/api.account.delete'
import { Route as ApiAccountExportRouteImport } from './routes/api.account.export'
import { Route as ApiImportDraftRouteImport } from './routes/api.import.draft'
import { Route as ApiImportStatusRouteImport } from './routes/api.import.status'
import { Route as ImgDidCidRouteImport } from './routes/img.$did.$cid'
import { Route as PHandleRkeyRouteImport } from './routes/p.$handle.$rkey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavingSubstackRoute = LeavingSubstackRouteImport.update({
  id: '/leaving-substack',
  path: '/leaving-substack',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenRoute = OpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123handleChar125IndexRoute =
  AtChar123handleChar125IndexRouteImport.update({
    id: '/@{$handle}/',
    path: '/@{$handle}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AtChar123handleChar125RkeyRoute =
  AtChar123handleChar125RkeyRouteImport.update({
    id: '/@{$handle}/$rkey',
    path: '/@{$handle}/$rkey',
    getParentRoute: () => rootRouteImport,
  } as any)
const AtChar123handleChar125RssDotxmlRoute =
  AtChar123handleChar125RssDotxmlRouteImport.update({
    id: '/@{$handle}/rss.xml',
    path: '/@{$handle}/rss.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDraftsRoute = ApiDraftsRouteImport.update({
  id: '/api/drafts',
  path: '/api/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportRoute = ApiImportRouteImport.update({
  id: '/api/import',
  path: '/api/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishRoute = ApiPublishRouteImport.update({
  id: '/api/publish',
  path: '/api/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportRoute = ApiReportRouteImport.update({
  id: '/api/report',
  path: '/api/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionRoute = ApiSubscriptionRouteImport.update({
  id: '/api/subscription',
  path: '/api/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthClientMetadataDotjsonRoute =
  OauthClientMetadataDotjsonRouteImport.update({
    id: '/oauth/client-metadata.json',
    path: '/oauth/client-metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const OauthJwksDotjsonRoute = OauthJwksDotjsonRouteImport.update({
  id: '/oauth/jwks.json',
  path: '/oauth/jwks.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountExportRoute = ApiAccountExportRouteImport.update({
  id: '/api/account/export',
  path: '/api/account/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportDraftRoute = ApiImportDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => ApiImportRoute,
} as any)
const ApiImportStatusRoute = ApiImportStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiImportRoute,
} as any)
const ImgDidCidRoute = ImgDidCidRouteImport.update({
  id: '/img/$did/$cid',
  path: '/img/$did/$cid',
  getParentRoute: () => rootRouteImport,
} as any)
const PHandleRkeyRoute = PHandleRkeyRouteImport.update({
  id: '/p/$handle/$rkey',
  path: '/p/$handle/$rkey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/import': typeof ImportRoute
  '/leaving-substack': typeof LeavingSubstackRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/open': typeof OpenRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/write': typeof WriteRoute
  '/@{$handle}/$rkey': typeof AtChar123handleChar125RkeyRoute
  '/@{$handle}/rss.xml': typeof AtChar123handleChar125RssDotxmlRoute
  '/api/drafts': typeof ApiDraftsRoute
  '/api/import': typeof ApiImportRouteWithChildren
  '/api/publish': typeof ApiPublishRoute
  '/api/report': typeof ApiReportRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/oauth/jwks.json': typeof OauthJwksDotjsonRoute
  '/@{$handle}/': typeof AtChar123handleChar125IndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/import/draft': typeof ApiImportDraftRoute
  '/api/import/status': typeof ApiImportStatusRoute
  '/img/$did/$cid': typeof ImgDidCidRoute
  '/p/$handle/$rkey': typeof PHandleRkeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/import': typeof ImportRoute
  '/leaving-substack': typeof LeavingSubstackRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/open': typeof OpenRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/write': typeof WriteRoute
  '/@{$handle}/$rkey': typeof AtChar123handleChar125RkeyRoute
  '/@{$handle}/rss.xml': typeof AtChar123handleChar125RssDotxmlRoute
  '/api/drafts': typeof ApiDraftsRoute
  '/api/import': typeof ApiImportRouteWithChildren
  '/api/publish': typeof ApiPublishRoute
  '/api/report': typeof ApiReportRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/oauth/jwks.json': typeof OauthJwksDotjsonRoute
  '/@{$handle}': typeof AtChar123handleChar125IndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/import/draft': typeof ApiImportDraftRoute
  '/api/import/status': typeof ApiImportStatusRoute
  '/img/$did/$cid': typeof ImgDidCidRoute
  '/p/$handle/$rkey': typeof PHandleRkeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/import': typeof ImportRoute
  '/leaving-substack': typeof LeavingSubstackRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/open': typeof OpenRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/write': typeof WriteRoute
  '/@{$handle}/$rkey': typeof AtChar123handleChar125RkeyRoute
  '/@{$handle}/rss.xml': typeof AtChar123handleChar125RssDotxmlRoute
  '/api/drafts': typeof ApiDraftsRoute
  '/api/import': typeof ApiImportRouteWithChildren
  '/api/publish': typeof ApiPublishRoute
  '/api/report': typeof ApiReportRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/oauth/jwks.json': typeof OauthJwksDotjsonRoute
  '/@{$handle}/': typeof AtChar123handleChar125IndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/import/draft': typeof ApiImportDraftRoute
  '/api/import/status': typeof ApiImportStatusRoute
  '/img/$did/$cid': typeof ImgDidCidRoute
  '/p/$handle/$rkey': typeof PHandleRkeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/home'
    | '/import'
    | '/leaving-substack'
    | '/login'
    | '/logout'
    | '/open'
    | '/policies'
    | '/privacy'
    | '/report'
    | '/settings'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/write'
    | '/@{$handle}/$rkey'
    | '/@{$handle}/rss.xml'
    | '/api/drafts'
    | '/api/import'
    | '/api/publish'
    | '/api/report'
    | '/api/stats'
    | '/api/subscription'
    | '/api/waitlist'
    | '/oauth/callback'
    | '/oauth/client-metadata.json'
    | '/oauth/jwks.json'
    | '/@{$handle}/'
    | '/api/account/delete'
    | '/api/account/export'
    | '/api/import/draft'
    | '/api/import/status'
    | '/img/$did/$cid'
    | '/p/$handle/$rkey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/home'
    | '/import'
    | '/leaving-substack'
    | '/login'
    | '/logout'
    | '/open'
    | '/policies'
    | '/privacy'
    | '/report'
    | '/settings'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/write'
    | '/@{$handle}/$rkey'
    | '/@{$handle}/rss.xml'
    | '/api/drafts'
    | '/api/import'
    | '/api/publish'
    | '/api/report'
    | '/api/stats'
    | '/api/subscription'
    | '/api/waitlist'
    | '/oauth/callback'
    | '/oauth/client-metadata.json'
    | '/oauth/jwks.json'
    | '/@{$handle}'
    | '/api/account/delete'
    | '/api/account/export'
    | '/api/import/draft'
    | '/api/import/status'
    | '/img/$did/$cid'
    | '/p/$handle/$rkey'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/home'
    | '/import'
    | '/leaving-substack'
    | '/login'
    | '/logout'
    | '/open'
    | '/policies'
    | '/privacy'
    | '/report'
    | '/settings'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/write'
    | '/@{$handle}/$rkey'
    | '/@{$handle}/rss.xml'
    | '/api/drafts'
    | '/api/import'
    | '/api/publish'
    | '/api/report'
    | '/api/stats'
    | '/api/subscription'
    | '/api/waitlist'
    | '/oauth/callback'
    | '/oauth/client-metadata.json'
    | '/oauth/jwks.json'
    | '/@{$handle}/'
    | '/api/account/delete'
    | '/api/account/export'
    | '/api/import/draft'
    | '/api/import/status'
    | '/img/$did/$cid'
    | '/p/$handle/$rkey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  ImportRoute: typeof ImportRoute
  LeavingSubstackRoute: typeof LeavingSubstackRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OpenRoute: typeof OpenRoute
  PoliciesRoute: typeof PoliciesRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  WriteRoute: typeof WriteRoute
  AtChar123handleChar125RkeyRoute: typeof AtChar123handleChar125RkeyRoute
  AtChar123handleChar125RssDotxmlRoute: typeof AtChar123handleChar125RssDotxmlRoute
  ApiDraftsRoute: typeof ApiDraftsRoute
  ApiImportRoute: typeof ApiImportRouteWithChildren
  ApiPublishRoute: typeof ApiPublishRoute
  ApiReportRoute: typeof ApiReportRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiSubscriptionRoute: typeof ApiSubscriptionRoute
  ApiWaitlistRoute: typeof ApiWaitlistRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OauthClientMetadataDotjsonRoute: typeof OauthClientMetadataDotjsonRoute
  OauthJwksDotjsonRoute: typeof OauthJwksDotjsonRoute
  AtChar123handleChar125IndexRoute: typeof AtChar123handleChar125IndexRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiAccountExportRoute: typeof ApiAccountExportRoute
  ImgDidCidRoute: typeof ImgDidCidRoute
  PHandleRkeyRoute: typeof PHandleRkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaving-substack': {
      id: '/leaving-substack'
      path: '/leaving-substack'
      fullPath: '/leaving-substack'
      preLoaderRoute: typeof LeavingSubstackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open': {
      id: '/open'
      path: '/open'
      fullPath: '/open'
      preLoaderRoute: typeof OpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$handle}/': {
      id: '/@{$handle}/'
      path: '/@{$handle}'
      fullPath: '/@{$handle}/'
      preLoaderRoute: typeof AtChar123handleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$handle}/$rkey': {
      id: '/@{$handle}/$rkey'
      path: '/@{$handle}/$rkey'
      fullPath: '/@{$handle}/$rkey'
      preLoaderRoute: typeof AtChar123handleChar125RkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$handle}/rss.xml': {
      id: '/@{$handle}/rss.xml'
      path: '/@{$handle}/rss.xml'
      fullPath: '/@{$handle}/rss.xml'
      preLoaderRoute: typeof AtChar123handleChar125RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drafts': {
      id: '/api/drafts'
      path: '/api/drafts'
      fullPath: '/api/drafts'
      preLoaderRoute: typeof ApiDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import': {
      id: '/api/import'
      path: '/api/import'
      fullPath: '/api/import'
      preLoaderRoute: typeof ApiImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish': {
      id: '/api/publish'
      path: '/api/publish'
      fullPath: '/api/publish'
      preLoaderRoute: typeof ApiPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report': {
      id: '/api/report'
      path: '/api/report'
      fullPath: '/api/report'
      preLoaderRoute: typeof ApiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription': {
      id: '/api/subscription'
      path: '/api/subscription'
      fullPath: '/api/subscription'
      preLoaderRoute: typeof ApiSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/client-metadata.json': {
      id: '/oauth/client-metadata.json'
      path: '/oauth/client-metadata.json'
      fullPath: '/oauth/client-metadata.json'
      preLoaderRoute: typeof OauthClientMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/jwks.json': {
      id: '/oauth/jwks.json'
      path: '/oauth/jwks.json'
      fullPath: '/oauth/jwks.json'
      preLoaderRoute: typeof OauthJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/export': {
      id: '/api/account/export'
      path: '/api/account/export'
      fullPath: '/api/account/export'
      preLoaderRoute: typeof ApiAccountExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import/draft': {
      id: '/api/import/draft'
      path: '/draft'
      fullPath: '/api/import/draft'
      preLoaderRoute: typeof ApiImportDraftRouteImport
      parentRoute: typeof ApiImportRoute
    }
    '/api/import/status': {
      id: '/api/import/status'
      path: '/status'
      fullPath: '/api/import/status'
      preLoaderRoute: typeof ApiImportStatusRouteImport
      parentRoute: typeof ApiImportRoute
    }
    '/img/$did/$cid': {
      id: '/img/$did/$cid'
      path: '/img/$did/$cid'
      fullPath: '/img/$did/$cid'
      preLoaderRoute: typeof ImgDidCidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$handle/$rkey': {
      id: '/p/$handle/$rkey'
      path: '/p/$handle/$rkey'
      fullPath: '/p/$handle/$rkey'
      preLoaderRoute: typeof PHandleRkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiImportRouteChildren {
  ApiImportDraftRoute: typeof ApiImportDraftRoute
  ApiImportStatusRoute: typeof ApiImportStatusRoute
}

const ApiImportRouteChildren: ApiImportRouteChildren = {
  ApiImportDraftRoute: ApiImportDraftRoute,
  ApiImportStatusRoute: ApiImportStatusRoute,
}

const ApiImportRouteWithChildren = ApiImportRoute._addFileChildren(
  ApiImportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  ImportRoute: ImportRoute,
  LeavingSubstackRoute: LeavingSubstackRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OpenRoute: OpenRoute,
  PoliciesRoute: PoliciesRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  WriteRoute: WriteRoute,
  AtChar123handleChar125RkeyRoute: AtChar123handleChar125RkeyRoute,
  AtChar123handleChar125RssDotxmlRoute: AtChar123handleChar125RssDotxmlRoute,
  ApiDraftsRoute: ApiDraftsRoute,
  ApiImportRoute: ApiImportRouteWithChildren,
  ApiPublishRoute: ApiPublishRoute,
  ApiReportRoute: ApiReportRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiSubscriptionRoute: ApiSubscriptionRoute,
  ApiWaitlistRoute: ApiWaitlistRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OauthClientMetadataDotjsonRoute: OauthClientMetadataDotjsonRoute,
  OauthJwksDotjsonRoute: OauthJwksDotjsonRoute,
  AtChar123handleChar125IndexRoute: AtChar123handleChar125IndexRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiAccountExportRoute: ApiAccountExportRoute,
  ImgDidCidRoute: ImgDidCidRoute,
  PHandleRkeyRoute: PHandleRkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
